[tool.ruff]
line-length = 120
src = ["wtesolver", "test"]

[tool.ruff.lint]
select = [
    "F", # pyflakes
    "B", # flake8-bugbear
    "SIM", # flake8-simplify
    "I", # isort
    "E", # pycodestyle-errors
    "D", # pydocstyle
]
ignore = [
    "D203", # numpy doc style
    "D213", # numpy doc style
    "B023", # function-uses-loop-variable
    "B008", # function-call-in-default-argument
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
